name: Build, Test and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create directories
        run: |
          mkdir -p bin
          mkdir -p target/classes
          mkdir -p target/test-classes

      - name: Compile Java source
        run: |
          javac -d target/classes src/*.java

      - name: Compile Java tests
        run: |
          # Télécharger JUnit si nécessaire
          wget -O junit-4.13.2.jar https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          wget -O hamcrest-core-1.3.jar https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
          
          # Compiler les tests
          javac -cp "junit-4.13.2.jar:hamcrest-core-1.3.jar:target/classes" -d target/test-classes tests/*.java

      - name: Run JUnit Tests
        run: |
          java -cp "junit-4.13.2.jar:hamcrest-core-1.3.jar:target/classes:target/test-classes" org.junit.runner.JUnitCore CalculatorTest

      - name: Create JAR file
        run: |
          cd target/classes
          jar -cfm ../simple-java-ci-1.0-SNAPSHOT.jar ../../manifest.txt *.class
        continue-on-error: true

      - name: Prepare deployment files
        run: |
          # Copier les fichiers web
          cp -r web/* ./
          
          # Créer un fichier de résultats des tests pour affichage web
          echo "<!DOCTYPE html><html><head><title>Test Results</title></head><body>" > test-results.html
          echo "<h1>✅ Tests Java réussis</h1>" >> test-results.html
          echo "<p>Build time: $(date)</p>" >> test-results.html
          echo "<p>Tous les tests JUnit sont passés avec succès!</p>" >> test-results.html
          echo "</body></html>" >> test-results.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4